export const ERROR_CODES = {
	//users
	USER_NOT_FOUND: "U_001",
	USER_INVALID_CREDENTIALS: "U_002",
	USER_UNAUTHORIZED: "U_003",
	USER_INSUFFICIENT_TYPE: "U_004",
	USER_INSUFFICIENT_DEPOSIT: "U_005",

	//products
	PRODUCT_NOT_FOUND: "P_001",
	PRODUCT_INSUFFICIENT_QUANTITY: "P_002",
};
